import type { Metadata } from "next";
import { inter } from "@/lib/fonts";
import "./globals.css";

// PLACEHOLDER GLOBAL METADATA
export const metadata: Metadata = {
  title: "Website",
  description: "Generated by steppable.com",
};

// PLACEHOLDER GLOBAL LAYOUT
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
