import {
  MessageCircleIcon,
  MousePointerClickIcon,
  RefreshCwIcon,
} from "lucide-react";
import { Metadata } from "next";

// PLACEHOLDER HOME METADATA
export const metadata: Metadata = {
  title: "Home | Website",
  description: "Generated by steppable.com",
};

// PLACEHOLDER HOME PAGE
export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
      <main className="flex flex-col gap-[32px] items-center">
        <svg
          width={50 * (608 / 729)}
          height={50}
          viewBox="0 0 608 729"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M272.233 0L380.334 0.263884L608 698.047L505.351 728.442L505.116 728.719L504.934 728.565L503.656 728.95L502.932 726.841L251.13 510.664L286.698 419.566L442.541 550.633L320.343 194.075L112.224 729L0 691.634L272.233 0Z"
            fill="black"
          />
        </svg>
        <div className="flex flex-col gap-4">
          <div className="flex flex-row gap-2">
            <MessageCircleIcon size={20} className="stroke-slate-500" />
            <p className="text-slate-500">Chat to create</p>
          </div>
          <div className="flex flex-row gap-2">
            <MousePointerClickIcon size={20} className="stroke-slate-500" />
            <p className="text-slate-500">Select to edit</p>
          </div>
          <div className="flex flex-row gap-2">
            <RefreshCwIcon size={20} className="stroke-slate-500" />
            <p className="text-slate-500">See your changes</p>
          </div>
        </div>
      </main>
    </div>
  );
}
